custom_components/xiaomi_home/miot/specs/specv2entity.py
test/test_common.py
test/test_lan.py
test/test_storage.py

- add some test case
- fix humidifier trans rule

merge: add test case

---

custom_components/xiaomi_home/miot/const.py

To fix the broken pipeline.
Add declaration for the Dutch translation
N/A

Fix Dutch translation declaration

---

README.md

fix table header misplacement: swap headers of table General Conversion of property

docs: fix table header misplacement

---

README.md
doc/README_zh.md

I saw this issue https://github.com/XiaoMi/ha_xiaomi_home/issues/536 where a user failed to update because the instructions are not complete. 
Add `git fetch` before `git checkout`.
N/A

doc: make git update guide more accurate

---

CHANGELOG.md
custom_components/xiaomi_home/manifest.json
custom_components/xiaomi_home/miot/specs/specv2entity.py

- Update changelog and version to v0.1.5b0
- Update code format

docs: update changelog and version to v0.1.5b0

---

custom_components/xiaomi_home/miot/lan/profile_models.yaml

Profile models are not complete, which will lead to abnormal local control of some devices. 
According to the background data, improve the list of profile models.

fix: the number of profile models updated from 660 to 823

---

test/check_rule_format.py
test/conftest.py
test/test_cloud.py
test/test_common.py
test/test_lan.py
test/test_mdns.py
test/test_network.py
test/test_spec.py
test/test_storage.py

-  Use the logging lib to uniformly manage the log output of test cases

style: using logging for test case log print

---

custom_components/xiaomi_home/miot/miot_cloud.py
custom_components/xiaomi_home/miot/miot_mdns.py

- Fix miot cloud miot_http.state error
- Fix miot mdns from_bytes error(did parse error)

fix: fix miot cloud and mdns error

---

custom_components/xiaomi_home/__init__.py
custom_components/xiaomi_home/miot/miot_client.py

- Support deleting devices on the device information page. After a device is deleted, if you want to add it again, you need to go to the configuration of the integration instance > Update device list to update.

feat: support remove device

---

custom_components/xiaomi_home/miot/specs/specv2entity.py

feat: add power properties trans

---

custom_components/xiaomi_home/cover.py
custom_components/xiaomi_home/miot/miot_spec.py
custom_components/xiaomi_home/miot/specs/spec_modify.yaml
custom_components/xiaomi_home/miot/specs/specv2entity.py

To solve #33 #379 #340 #401 
Add the motor controller and the airer as the cover entity.

feat: add device with motor-control service as cover entity

---

custom_components/xiaomi_home/fan.py

fix: wind-reverse format type

---

custom_components/xiaomi_home/manifest.json

fix: paho-mqtt version

---

custom_components/xiaomi_home/climate.py
custom_components/xiaomi_home/miot/miot_spec.py
custom_components/xiaomi_home/miot/specs/spec_modify.yaml

To solve #802 #791
Conversion rules:
The on property of the thermostat service -> The hvac mode of the climate entity
The mode property of the thermostat service -> The preset mode of the climate entity

feat: thermostat preset mode

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

fix: xiaomi.aircondition.m9 humidity-range unit

---

custom_components/xiaomi_home/miot/specs/specv2entity.py

To solve #877 
- Add conversion rules for the air-conditioner service and the air-fresh service.

feat: add new service conversion rules

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

修复一些specs
- [lumi.gateway.mcn001](https://home.miot-spec.com/spec/lumi.gateway.mcn001)
- [qmi.plug.psv3](https://home.miot-spec.com/spec/qmi.plug.psv3)
- [lumi.motion.acn001](https://home.miot-spec.com/spec/lumi.motion.acn001)
- [izq.sensor_occupy.24](https://home.miot-spec.com/spec/izq.sensor_occupy.24)
- [linp.sensor_occupy.hb01](https://home.miot-spec.com/spec/linp.sensor_occupy.hb01)
- [yunmi.waterpuri.s20](https://home.miot-spec.com/spec/yunmi.waterpuri.s20)

fix: fix some specs

---

custom_components/xiaomi_home/climate.py

#952 
Fixed **_attr_fan_modes** display initialization problem.

fix:Fixed initialization problem of _attr_fan_modes.

---

custom_components/xiaomi_home/miot/miot_client.py

修正网络状态变化（如路由器、光猫重启，重新拨号等）导致的设备状态不更新问题。
Fix device state not being updated caused by network change, such as router or modem rebooting, PPPoE redialing.
Close #941 #973 #922 #989 #686 #847 #909 #891 #680 #500
当网络状况发生变化时，会触发`MIoTClient`的`__update_device_msg_sub`。
`__update_device_msg_sub` of `MIoTClient` will be triggered, when network changed.
https://github.com/XiaoMi/ha_xiaomi_home/blob/2f619ff51d464ebac5b351a3d4f6590c1c02d094/custom_components/xiaomi_home/miot/miot_client.py#L940
该方法首先取消了旧的订阅，然后从新的来源订阅。
This method unsubs old subscription first, then subs from new source.
https://github.com/XiaoMi/ha_xiaomi_home/blob/2f619ff51d464ebac5b351a3d4f6590c1c02d094/custom_components/xiaomi_home/miot/miot_client.py#L968-L993
但由于是网络状况变化触发的操作，旧的loop可能已处于关闭状态，unsub抛出`RuntimeError('Event loop is …

fix: ignore 'Event loop is closed' when unsub a closed event loop

---

custom_components/xiaomi_home/config_flow.py
custom_components/xiaomi_home/miot/miot_cloud.py

feat: import shared devices

---

custom_components/xiaomi_home/config_flow.py

fix: update device list error when there is no shared devices

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

https://github.com/XiaoMi/ha_xiaomi_home/issues/1015

add device zhimi.fan.v3  prop.2.2

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

Reverts XiaoMi/ha_xiaomi_home#1027

Revert "add device zhimi.fan.v3  prop.2.2"

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

fix https://github.com/XiaoMi/ha_xiaomi_home/issues/1015

fix: zhimi.fan.v3 spec

---

custom_components/xiaomi_home/fan.py

fix: set fan on/off state before set the percentage

---

custom_components/xiaomi_home/miot/specs/spec_modify.yaml

fix: linp.magnet.m1 contact state in sensor text

---

custom_components/xiaomi_home/miot/i18n/de.json
custom_components/xiaomi_home/miot/i18n/en.json
custom_components/xiaomi_home/miot/i18n/es.json
custom_components/xiaomi_home/miot/i18n/fr.json
custom_components/xiaomi_home/miot/i18n/it.json
custom_components/xiaomi_home/miot/i18n/ja.json
custom_components/xiaomi_home/miot/i18n/nl.json
custom_components/xiaomi_home/miot/i18n/pt-BR.json
custom_components/xiaomi_home/miot/i18n/pt.json
custom_components/xiaomi_home/miot/i18n/ru.json
custom_components/xiaomi_home/miot/i18n/zh-Hans.json
custom_components/xiaomi_home/miot/i18n/zh-Hant.json
custom_components/xiaomi_home/miot/miot_client.py

- Show notifications when the local connection to the central hub gateway gets changed.

feat: add notifications for the local connection to the central hub gateway

---

custom_components/xiaomi_home/vacuum.py

A MIoT-Spec-V2 property having value-list is storaged in xiaomi_home with its elements' name, value and description. The element name is the MIoT-Spec-V2 description. The element value is the MIoT-Spec-V2 value. The element description is the multi-langurage text in the user's langurage. So xiaomi_home shall use the name rather than the description to determine the status of the vacuum.
- Fix the vacuum status so that the vacuum activity will not always be idle.
- Eliminate Home Assistant Core warings about the vacuum activity.

fix: vacuum status
