custom_components/xiaomi_home/miot/miot_device.py
Move unit imports inside function 和 add fallback for older versions. Resolves #123
=> fix: handle UnitOfConductivity import

install.sh
When the first time to install home assistant and ssh to it, there is no "/config/custom_components/" directory in the homeassistant docker. At this time, if the user runs the install.sh, there will not create a "xiaomi_home" directory in the "/config/custom_components/" path. Instead, the file structure will be like below:
```
.
├── custom_components
│   ├── __init__.py
│   ├── binary_sensor.py
│   ├── button.py
│   ├── climate.py
│   ├── config_flow.py
│   ├── cover.py
│   ├── event.py
│   ├── fan.py
│   ├── humidifier.py
│   ├── light.py
│   ├── manifest.json
│   ├── miot
│   ├── notify.py
│   ├── number.py
│   ├── select.py
│   ├── sensor.py
│   ├── switch.py
│   ├── text.py
│   ├── translations
│   ├── vacuum.py
│   └── water_heater.py
```
And if user wants to search the Xiaomi Home …
=> fix: directory copy issue

install.sh
The old install logic uses a if logic to handle missing root conditions. Which is not straightforward and unnecessary. 
* Avoid switching directories.
* Use variables to avoid repeating path names.
* Use `mkdir -p` instead to make sure the target root is created.
* Tested the script with local folders.
=> Simplify the install logic

custom_components/xiaomi_home/miot/miot_storage.py, doc/README_zh.md
docs: fix the incorrect link of README_zh.md about changelog
fix: error messages and incorrent return value which could possibly lead to crash in mint_storage.py
=> Fix README_zh and miot_storage

README.md, doc/README_zh.md, hacs.json
fix HASS core version requirements in hacs.json and documents
=> fix: HASS core version requirements

custom_components/xiaomi_home/miot/miot_cloud.py
- Fix miot cloud token refresh logic
=> fix: fix miot cloud token refresh

custom_components/xiaomi_home/climate.py, custom_components/xiaomi_home/config_flow.py, custom_components/xiaomi_home/event.py, custom_components/xiaomi_home/fan.py, custom_components/xiaomi_home/humidifier.py, custom_components/xiaomi_home/light.py, custom_components/xiaomi_home/miot/common.py, custom_components/xiaomi_home/miot/miot_client.py, custom_components/xiaomi_home/miot/miot_cloud.py, custom_components/xiaomi_home/miot/miot_device.py, custom_components/xiaomi_home/miot/miot_error.py, custom_components/xiaomi_home/miot/miot_ev.py, custom_components/xiaomi_home/miot/miot_mips.py, custom_components/xiaomi_home/miot/miot_spec.py, custom_components/xiaomi_home/miot/miot_storage.py, custom_components/xiaomi_home/sensor.py, custom_components/xiaomi_home/water_heater.py, test/test_lan.py
- Fix wrong use of any and Any
- Fix wrong use of aiohttp session close
=> fix: fix type error, wrong use of any and Any

README.md, doc/README_zh.md
In the original HACS 2.0.1, 'Category' is expressed as 'Type'
=> docs: amend HACS installation

custom_components/xiaomi_home/miot/miot_device.py
- fix unit_convert AttributeError, Change to catch all Exception.
Error log:
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'
=> fix: fix unit convert attribute error

custom_components/xiaomi_home/miot/miot_device.py
Fix #376 
- 忽略spec中未定义的piid并继续处理后续的arguments
- 错误日志改为debug日志
=> fix: ignore undefined piid and keep processing following arguments

custom_components/xiaomi_home/miot/specs/multi_lang.json
To solve confusing action name in #254
=> fix: lumi.switch.acn040 identify service translation of zh-Hans

custom_components/xiaomi_home/manifest.json
Per knoop7's suggestion. Removing dependency on aiohttp. aiohttp is a dependency of the home assistant core. So this should not break anything.
Resolving https://github.com/XiaoMi/ha_xiaomi_home/issues/308
=> misc: remove duplicate dependency

custom_components/xiaomi_home/notify.py, custom_components/xiaomi_home/text.py
使用 yaml 来解析 action 参数，以获得更多的兼容性。
- 完全兼容之前的 json 格式参数，用户无迁移成本
- `[str1, 'str2', 123, true, 'on', 'yes']`
- `on/off/yes/no`等词会被解析成 bool，需要引号包裹
- action 仅有一个参数时，支持直接传递字符串，无需传递`'["xxx"]'`
```yaml
action: notify.send_message
data:
entity_id: notify.xiaomi_cn_xxxx
message: 我是小爱
```
=> feat: use yaml to parse action params

custom_components/xiaomi_home/miot/miot_cloud.py
- When refreshing the token fails, it is able to print out the message content returned by the cloud.
=> fix: update miot cloud raise error msg

custom_components/xiaomi_home/light.py, custom_components/xiaomi_home/miot/specs/spec_filter.json
In the [spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:switch:0000A003:lemesh-sw3f13:1:0000C810) definition of `lemesh.switch.sw3f13`, the mode of indicator-light is defined as the value-range of 0 to 4294967295(possibly used for setting the do-not-disturb mode of the indicator light and the do-not-disturb time period.
), which leads to 4294967295 modes being generated during the re-conversion process, thereby causing an exception.
```json
{
"iid": 3,
"type": "urn:miot-spec-v2:property:mode:00000008:lemesh-sw3f13:1",
"description": "Mode",
"format": "uint32",
// ...
"value-range": [
0,
4294967295,
1
],
// ...
}
```
---
Restrict the number of modes according to the mode definition of all light types on the line.
Statistics of all the values of light.mode …
=> feat: limit *light.mode count (value-range)

custom_components/xiaomi_home/miot/miot_cloud.py, custom_components/xiaomi_home/miot/specs/spec_filter.json
All devices with did starting with "miwifi." are routers that interface between the Xiaomi home cloud and the Xiaomi router cloud. These routers have all defined functions but have not been implemented, so they are all filtered out; some routers that are not "miwifi.*" also have this problem.
Filter the devices whose did starts with "miwifi".
**After the update, it is necessary to enter the integrated instance: Configuration > Update Device Information, and delete the unavailable devices.**
=> feat: filter miwifi.* devices

CHANGELOG.md, custom_components/xiaomi_home/manifest.json
This version will cause some Xiaomi routers that do not support access (#564) to become unavailable. You can update the device list in the configuration or delete it manually.
- Fan entity support direction ctrl [#556](https://github.com/XiaoMi/ha_xiaomi_home/pull/556)
- Filter miwifi.* devices and xiaomi.router.rd03 [#564](https://github.com/XiaoMi/ha_xiaomi_home/pull/564)
- Fix multi ha instance login [#560](https://github.com/XiaoMi/ha_xiaomi_home/pull/560)
- Fix fan speed [#464](https://github.com/XiaoMi/ha_xiaomi_home/pull/464)
- The number of profile models updated from 660 to 823. [#583](https://github.com/XiaoMi/ha_xiaomi_home/pull/583)
=> docs: update changelog and version to v0.1.5b1

test/conftest.py, test/test_cloud.py
- Add test case for user cert, the user cert can be used to connect to the Xiaomi Central Gateway (only available in the CN region).
- Improve test case for miot_cloud.py
=> test: add test case for user cert

custom_components/xiaomi_home/miot/miot_mips.py, test/test_mdns.py, test/test_mips.py
- Add test case for miot mips
- Improve mips reconnect logic
- Update mdns test case
=> feat: change mips reconnect logic & add mips test case

CHANGELOG.md, custom_components/xiaomi_home/manifest.json
- Support binary sensors to be displayed as text sensor entities and binary sensor entities. [#592](https://github.com/XiaoMi/ha_xiaomi_home/pull/592)
- Add miot cloud test case. [#620](https://github.com/XiaoMi/ha_xiaomi_home/pull/620)
- Add test case for user cert. [#638](https://github.com/XiaoMi/ha_xiaomi_home/pull/638)
- Add mips test case & Change mips reconnect logic. [#641](https://github.com/XiaoMi/ha_xiaomi_home/pull/641)
- Support remove device. [#622](https://github.com/XiaoMi/ha_xiaomi_home/pull/622)
- Support italian translation. [#183](https://github.com/XiaoMi/ha_xiaomi_home/pull/183)
- Refactor miot spec. [#592](https://github.com/XiaoMi/ha_xiaomi_home/pull/592)
- Refactor miot mips & fix type errors. [#365](https://github.com/XiaoMi/ha_xiaomi_home/pull/365)
- Using …
=> docs: update changelog and version to v0.1.5b2

custom_components/xiaomi_home/climate.py, custom_components/xiaomi_home/cover.py, custom_components/xiaomi_home/fan.py, custom_components/xiaomi_home/light.py, custom_components/xiaomi_home/miot/miot_device.py, custom_components/xiaomi_home/water_heater.py
- Fixed water heater error based on #593 
- Fixed some type error
- Update miot device set_property_async logic
=> fix: fix water heater error & some type error

custom_components/xiaomi_home/fan.py
=> fix: fan level with value-list & fan reverse

custom_components/xiaomi_home/climate.py, custom_components/xiaomi_home/miot/specs/specv2entity.py
Add support for `electric-blanket` as `climate`.
Tested with device [`isleep.blanket.hs2401`](https://home.miot-spec.com/spec/isleep.blanket.hs2401)
=> feat: add support for electric blanket

doc/README_zh.md
In the English documentation, the file path is `custom_components/xiaomi_home/miot/specs`,
In the Chinese documentation, the file path is `custom_components/xiaomi_home/translations/`
After checking, `custom_components/xiaomi_home/miot/specs` is the correct path.
=> fix: Error in "多语言支持" in Chinese documentation

custom_components/xiaomi_home/miot/miot_spec.py
Fix issue where `precision=0` was incorrectly defaulting to `1`.
=> fix: fix sensor display precision

custom_components/xiaomi_home/miot/miot_mips.py
fix #651 
fix #667 
---
追踪了一下，问题出在 有些设备上报事件的时候没有`arguments`参数，在这里被拦住了。（例如 [米家夜灯2 蓝牙版 (yeelink.light.nl1)](https://home.miot-spec.com/spec/yeelink.light.nl1) 和 [小米人体传感器2 (lumi.motion.bmgl01)](https://home.miot-spec.com/spec/lumi.motion.bmgl01)）
简单做了一下默认值处理，经测试可行。
=> fix: some `event:motion-detected` does not contain `'arguments'`

custom_components/xiaomi_home/miot/miot_device.py, custom_components/xiaomi_home/miot/miot_spec.py, custom_components/xiaomi_home/miot/specs/specv2entity.py
When user turn off lights in an area, the indicator-light will also be turned off.
当用户通过 `light.turn_on` 或者 `light.turn_off` 控制某个房间的时候，指示灯也会被一起控制。
因为指示灯现在也是 `light`，添加 `entity_cateory`: `EntityCategory.CONFIG` 可以解决这个问题。
https://github.com/XiaoMi/ha_xiaomi_home/discussions/696
https://developers.home-assistant.io/docs/core/entity/#registry-properties
> Classification of a non-primary entity. Set to EntityCategory.CONFIG for an entity that allows changing the configuration of a device, for example, a switch entity, making it possible to turn the background illumination of a switch on and off. Set to EntityCategory.DIAGNOSTIC for an entity exposing some configuration parameter or diagnostics of a device but does not allow changing it, for example, a sensor showing RSSI or MAC address.
Added …
=> feat: add entity_category for indicator-light

custom_components/xiaomi_home/cover.py
Fix: #785 
此PR修复了 [linp.wopener.wd1lb](https://home.miot-spec.com/spec/linp.wopener.wd1lb) 会卡在 `正在打开` 和 `正在关闭` 状态的问题。
关于 领普平移推窗器WD1 的几个表现细节参考：https://github.com/XiaoMi/ha_xiaomi_home/pull/688#discussion_r1969860606
---
这里通过在一些关键节点手动设置 `_attr_is_opening` 和 `_attr_is_closing` 的方式来更新状态。
这种做法可能不适合所有设备，由于我也没有其他设备可以测试，所以先把这版修改放上来。
这里限制了只会影响 ”没有 `status` 且有 `current_position`“ 的设备
=> fix: opening and closing for linp.wopener.wd1lb

custom_components/xiaomi_home/miot/miot_device.py, custom_components/xiaomi_home/number.py, custom_components/xiaomi_home/sensor.py
建议：有 `device_class` 的实体不要设置 icon 了，HA有一套默认的图标。这样例如电池的实体图标也会随着电量自动变化。
https://github.com/XiaoMi/ha_xiaomi_home/discussions/278
=> feat: avoid setting icon when device_class is defined

custom_components/xiaomi_home/event.py, custom_components/xiaomi_home/miot/miot_mips.py, custom_components/xiaomi_home/miot/miot_spec.py, custom_components/xiaomi_home/miot/specs/spec_modify.yaml
To solve #736 #864 
- Modify the name of the MIoT-Spec-V2 property instance.
- Necessary logs for the event entity.
=> fix: MIoT-Spec-V2 conflicts of xiaomi.fan.p5 and mike.bhf_light.2

custom_components/xiaomi_home/climate.py, custom_components/xiaomi_home/miot/specs/specv2entity.py
To solve #868 #822 #814 
- Use the preset mode to display the mode of the ptc bath heater.
- Add the environment temperature of the ptc bate heater in the conversion rule.
=> feat: convert the mode of the ptc bath heater to the preset mode

custom_components/xiaomi_home/climate.py, custom_components/xiaomi_home/miot/specs/spec_modify.yaml
To solve #877 #886 
- The device with multiple climate services like air-conditioner, thermostat, heater and electric-blanket will be converted to several climate entities. These entities' on/off switch is linked to the on property of the air-conditioner service, the thermostat service, the heater and the electric-blanket serivce respectively. 
- [temperature_unit is required by the climate entity](https://developers.home-assistant.io/docs/core/entity/climate/#properties). If temperature_unit is not specified, the entity will not be added to hass successfully.
=> fix: on/off feature initialization

custom_components/xiaomi_home/miot/specs/multi_lang.json, custom_components/xiaomi_home/miot/specs/spec_modify.yaml
Fix the unit and icon for hhcc-v1 to let Home Assistant correctly display the history chart.
操作错了，把上一个PR关了，写`name: moisture`是因为只改icon没反应
=> fix: correct unit,icon and translations for hhcc-v1

custom_components/xiaomi_home/binary_sensor.py, custom_components/xiaomi_home/miot/specs/specv2entity.py
雨感状态、接触状态、有人无人状态 实体类型调整为 `binary_sensor`，并添加对应的 `device_class`。
fix #206 
fix #741 
fix #775 
fix #809 
另外也有相当多的讨论都提出了相同的建议：
https://github.com/XiaoMi/ha_xiaomi_home/discussions/914
https://github.com/XiaoMi/ha_xiaomi_home/discussions/897
https://github.com/XiaoMi/ha_xiaomi_home/discussions/653
https://github.com/XiaoMi/ha_xiaomi_home/discussions/485
https://github.com/XiaoMi/ha_xiaomi_home/discussions/449
https://github.com/XiaoMi/ha_xiaomi_home/discussions/345
https://github.com/XiaoMi/ha_xiaomi_home/discussions/184
=> feat: make submersion-state, contact-state, occupancy-status as binary_sensor

custom_components/xiaomi_home/climate.py
To solve [#796](https://github.com/XiaoMi/ha_xiaomi_home/issues/796#issuecomment-2692662072)
- Set `_attr_hvac_action` for the AirConditioner, the Heater and the ElectricBlanket.
=> feat: support _attr_hvac_action of the climate entity

custom_components/xiaomi_home/miot/specs/spec_modify.yaml
这两个设备用了 `status` 来定义开关状态，这里把 name 修改成 `contact-state`，这样可以作为 `binary_sensor` 来显示。
Fix #975
=> fix(spec): contact-state for linp.magnet.m1 and loock.safe.v1

custom_components/xiaomi_home/miot/specs/specv2entity.py
把空气净化器作为风扇显示。
air-purifier 和 fan 有非常多相似的地方，HA上也有很多其它集成都是把空气净化器设计成`fan`的。
已在 `zhimi.airp.ua1` 上测试
=> feat: make air-purifier as fan

custom_components/xiaomi_home/humidifier.py
To solve #525 
The target-humidity property is not a required property in the humidifier service. If a humidifier does not have the target-property, the `prop` param of `get_prop_value` is None.
- Support the action (HumidifierAction).
=> fix: the humidifier get_prop_value when the property is None

custom_components/xiaomi_home/miot/miot_lan.py
修复局域网控制下中文显示为unicode码问题，关联issue https://github.com/XiaoMi/ha_xiaomi_home/issues/555
=> fix: Chinese encoding under LAN Control

custom_components/xiaomi_home/miot/miot_client.py, custom_components/xiaomi_home/miot/miot_spec.py, custom_components/xiaomi_home/miot/specs/spec_modify.yaml
#980 : When xiaomi_home set the target temperature property (siid=3, piid=4) to 25.0 of lumi.acpartner.mcn04 through the LAN control, the device responded code=-4005 indicating that the value is invalid. I suspect that the device only supports a int value rather than a float value.
Modifying the MIoT-Spec-V2 property format by spec_modify.yaml
=> feat: modify MIoT-Spec-V2 property format

custom_components/xiaomi_home/miot/miot_spec.py, custom_components/xiaomi_home/miot/specs/spec_add.json, custom_components/xiaomi_home/miot/specs/specv2entity.py, custom_components/xiaomi_home/water_heater.py
#202 #745 : A switch entity for the water heater on/off status is helpfull for using the device in homekit.
- Add a switch entity alongside the water heater entity of zimi.waterheater.h03 and xiaomi.waterheater.yms2.
- Fix the maximum temperature, the minimum temperature and the temperature step that can be set.
=> feat: add an alongside switch entity for the water heater

custom_components/xiaomi_home/miot/miot_mips.py
To solve #1106 
When the mqtt client disconnects from the cloud or the central hub gateway, the unsubscribing operation gets a result of MQTT_ERR_NO_CONN(4). This error message can be ignored.
=> fix: the error "mips unsub internal error, 4, None"

custom_components/xiaomi_home/water_heater.py
The water heater entity must support the `OPERATION_MODE` feature even though the device MIoT-Spec-V2 does not contain a mode property, for the water heater on/off state can only be set by the operation mode setting entry.
- Support the `OPERATION_MODE` feature in all situations.
=> fix: the operation mode when the device does not have a mode property

custom_components/xiaomi_home/miot/miot_mips.py
If the reconnect delay time is not set to the default `MIPS_RECONNECT_INTERVAL_MIN` when xiaomi_home client is connected to the broker, the next delay time will alway be `MIPS_RECONNECT_INTERVAL_MAX` after several disconnections.
- The default reconnect delay time is set to be 10 seconds.
- Set the reconnect delay time to be `MIPS_RECONNECT_INTERVAL_MIN` when the client is connected to the broker.
=> fix: reconnect delay time

custom_components/xiaomi_home/miot/const.py, custom_components/xiaomi_home/miot/miot_cloud.py, custom_components/xiaomi_home/miot/miot_device.py, custom_components/xiaomi_home/miot/miot_mips.py, custom_components/xiaomi_home/miot/specs/spec_filter.yaml
Xiaomi central hub gateway pushes all the online devices in the available device list to xiaomi_home no matter that some devices, like the infrared ray remote, the device without a valid MIoT-Spec-V2, are not supported by xiaomi_home. xiaomi_home must filter out the unsupport devices to avoid unnecessay device online notice. 
- Filter out unsupported device models at getting the device list from the MIoT cloud and Xiaomi central hub gateway.
- Delete unused logs.
=> feat: exclude unsupported model

custom_components/xiaomi_home/cover.py, custom_components/xiaomi_home/miot/miot_mips.py
As of July 7, 2025, the statistical results are as follows.
| Circumstance | Number |
|---|---|
| airer service has only one status property | 167 |
| airer service has multiple status properties | 5 |
| airer service has no status property | 31 |
| The value-list descriptions of the status property in a airer service<br>(Remove the spaces, hyphens, and other punctuation marks in the phrases, and convert all letters to lowercase.) | Number |
|---|---|
|	down	|	108	|
|	stop	|	96	|
|	rising	|	85	|
|	pause	|	57	|
|	up	|	53	|
|	idle	|	36	|
|	busy	|	21	|
|	falling	|	19	|
|	settingheight	|	17	|
|	stopathighest	|	16	|
|	stopatlowest	|	16	|
|	stopatmiddle	|	14	|
|	lower	|	10	|
|	stopupperlimit	|	7	|
|	stoplowerlimit	|	7	|
|	dowm	|	7	|
|	rise	|	6	|
|	stopped	|	5	|
|	upper	|	4	|
|	upperlimitstop	| …
=> fix: airer status for cover entity

custom_components/xiaomi_home/miot/miot_mips.py, custom_components/xiaomi_home/miot/specs/spec_add.json, custom_components/xiaomi_home/miot/specs/spec_filter.yaml
In #1334, xiaomi_home does not subscribe the device upstream message topics of xiaomi.airer.pro3. In #1295, xiaomi_home does not subscribe the device upstream message topics of lumi.acpartner.mcn02. In these issues, users both import a Narwal vacuum which has a large number of MIoT-Spec-V2 readable properties. The request to get the latest property values of Narwal vacuum cost as long as 17 seconds and most of the property values are failed to fetch with the third party cloud error "property not supported". I suspect that thread blocking prevented the subscription operation.
narwa.vacuum.001 only supports MIoT-Spec-V2 property of 2.2, 2.3, 2.17, 2.18, 2.71, 11.1 and 11.2.
narwa.vacuum.ax11 only supports MIoT-Spec-V2 property of 2.2, 2.3, 2.4, 2.17, 2.18, 2.71, 11.1 and 11.2.
- Delete alll …
=> fix: delete all unsupported MIoT-Spec-V2 instances of Narwal vacuum

custom_components/xiaomi_home/miot/miot_spec.py
The integer property value must comply with the value step defined in the value-range field, otherwise the device will response error when setting the property with a wrong value.
- Correct the integer value to comply with the value step.
=> fix: integer value step

custom_components/xiaomi_home/binary_sensor.py
The contact-state property of linp.magnet.m1 is modified by [spec_modify.yaml](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/custom_components/xiaomi_home/miot/specs/spec_modify.yaml#L218), while its value format is not changed and is still int. The int value 0 or 1 is always not False.
- Convert the contact-state property value format to bool.
=> fix: contact-state value format
